export const ROUTES = {
    MAIN: '/',
    SIGNIN: '/registration'
}

export const actionTypes = {
    CHANGE_NAME: 'CHANGE_NAME',
    CHANGE_EMAIL: 'CHANGE_EMAIL',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',

    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    CHANGE_TOKEN: 'CHANGE_TOKEN',
    CHANGE_USERID: 'CHANGE_USERID',

    GET_EMAIL: 'GET_EMAIL',
    GET_PASSWORD: 'GET_PASSWORD',
    GET_NAME: 'GET_NAME',

    CLEAR_STATE: 'CLEAR_STATE',

    
}