export const ROUTES = {
    MAIN: '/',
    SIGNIN: '/registration',
    ADD: '/add',
    POSTS: '/posts'
}

export const actionTypes = {
    CHANGE_NAME: 'CHANGE_NAME',
    CHANGE_EMAIL: 'CHANGE_EMAIL',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',

    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    CHANGE_TOKEN: 'CHANGE_TOKEN',
    CHANGE_USERID: 'CHANGE_USERID',

    GET_EMAIL: 'GET_EMAIL',
    GET_PASSWORD: 'GET_PASSWORD',
    GET_NAME: 'GET_NAME',

    CHANGE_POST_PICTURE: 'CHANGE_POST_PICTURE',
    CHANGE_POST_TITLE: 'CHANGE_POST_TITLE',
    CHANGE_POST_PRICE: 'CHANGE_POST_PRICE',
    CHANGE_POST_DESCRIPTION: 'CHANGE_POST_DESCRIPTION',
    CHANGE_POST_CONTACTS: 'CHANGE_POST_CONTACTS',
    
    ADD_POST_START: 'ADD_POST_START',
    ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
    ADD_POST_FAILURE: 'ADD_POST_FAILURE',

    GET_POST_START: 'GET_POST_START',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    GET_POST_FAILURE: 'GET_POST_FAILURE',

    GET_ALL_POSTS_START: 'GET_ALL_POSTS_START',
    GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
    GET_ALL_POSTS_FAILURE: 'GET_ALL_POSTS_FAILURE',

    CHANGE_ADDING_POST_STATUS: 'CHANGE_ADDING_POST_STATUS',
    RETURN_ADDING_POST_STATUS: 'RETURN_ADDING_POST_STATUS',

    SEARCH_POST: 'SEARCH_POST',

    GET_POST_ID: 'GET_POST_ID',

    CLEAR_STATE: 'CLEAR_STATE'    
}